// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.equisettle.common.domain;

import com.equisettle.common.domain.Mediator;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Mediator_Roo_Configurable {
    
    declare @type: Mediator: @Configurable;
    
}
